version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: serialport
    versions:
    - 9.0.6
