module.exports.OPENTHERM_IDS = {
    0: { name: "flame_status",                      type: "flag8" },
    1:   { name: "control_setpoint",                type: "f8.8" },
    9:   { name: "remote_override_setpoint",        type: "f8.8" },
    14:  { name: "max_relative_modulation_level",   type: "f8.8" },
    16:  { name: "room_setpoint",                   type: "f8.8" },
    17:  { name: "relative_modulation_level",       type: "f8.8" },
    18:  { name: "ch_water_pressure",               type: "f8.8" },
    24:  { name: "room_temperature",                type: "f8.8" },
    25:  { name: "boiler_water_temperature",        type: "f8.8" },
    26:  { name: "dhw_temperature",                 type: "f8.8" },
    27:  { name: "outside_temperature",             type: "f8.8" },
    28:  { name: "return_water_temperature",        type: "f8.8" },
    56:  { name: "dhw_setpoint",                    type: "f8.8" },
    57:  { name: "max_ch_water_setpoint",           type: "f8.8" },
    116: { name: "burner_starts",                   type: "u16" },
    117: { name: "ch_pump_starts",                  type: "u16" },
    118: { name: "dhw_pump_starts",                 type: "u16" },
    119: { name: "dhw_burner_starts",               type: "u16" },
    120: { name: "burner_operation_hours",          type: "u16" },
    121: { name: "ch_pump_operation_hours",         type: "u16" },
    122: { name: "dhw_pump_valve_operation_hours",  type: "u16" },
    123: { name: "dhw_burner_operation_hours",      type: "u16" },
}